### PR TITLE
Add support for PROPFIND action

### PR DESCRIPTION
**Pull request by boeingo**
When trying to use `PROPFIND` HTTP verb I realized that `Patron` doesn't support it. Is there a reason for that? By the way, can you consider merging this one? Any suggestions are welcome :smile:

### CODE REVIEW

**Comment by toland** [comment]
LGTM. @julik?

**Comment by julik** [comment]
LGTM as well, but what about the other WEBDAV methods (PROPPATCH, COPY, LOCK, UNLOCK..)? Maybe add them too?

**Comment by wevtimoteo** [comment]
Nice catch @julik, as we already have `COPY` I'll implement them following this [list](https://msdn.microsoft.com/en-us/library/aa142917(v=exchg.65).aspx). WDYT?

**Comment by julik** [comment]
Yep, go ahead!

**Comment by julik** [comment]
@boeingo @wevtimoteo was there any progress on this? TBH, I think building a WebDAV client might also be a case when the library (the DAV client) can use `request` directly, without having helper methods for each HTTP verb.

**Comment by wevtimoteo** [comment]
Hi @julik, I was planning to resume this work tomorrow for remaining WebDAV verbs. So if I get the idea properly, we can add some examples in Wiki showing how to use Patron for other HTTP verbs and closing this one, WDYT?

**Comment by julik** [comment]
Yes, I think this is a better idea ❤️

**Comment by wevtimoteo** [comment]
@julik Okay, so we can close this one :)

**Comment by julik** [comment]
Thank you ❤️

**Pull request closed without merging**
