### PR TITLE
require securerandom in session_spec

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by julik** [comment]
Why is this necessary? You had problems when running `session_spec.rb` in an editor?

**Comment by mmoll** [comment]
I had errors running that test under Ruby 2.3 on  Debian

**Comment by julik** [comment]
Thanks, will also add it to the Travis matrix

**Comment by julik** [comment]
@mmoll I have solved it a little differently in https://github.com/toland/patron/commit/f9b91c2979ee084957d4465a88058d47e13ed564 - can you check if that works for you?

**Comment by mmoll** [comment]
it does, thanks!

**Comment by julik** [comment]
🚀  Thanks for checking!

**Pull request closed without merging**
