### PR TITLE
Fixing Charset Issues

### PR DESCRIPTION
**Pull request by AlexRiedler**
This is a little bit of fixes on #122 ; I am not sure if there is more work to be done. Would be willing to put in more effort to get this going.

### CODE REVIEW

**Comment by AlexRiedler** [comment]
I think there was also some talk about doing force utf-8 instead on body; if no charset provided; and use non-reencoded back function as well?

**Comment by toland** [comment]
@AlexRiedler Thanks for the contribution!

Everything looks reasonable to me, but I am going to defer to @julik.

**Comment by julik** [comment]
Good stuff @AlexRiedler I need to look into this in more detail because I remember I stalled in my original PR when I realised there was fundamentally no _better_ way without doing stuff you do not expect. Hope I can find some time for this until Monday.

**Comment by AlexRiedler** [comment]
@julik just a friendly reminder; I know how busy it can get :)

**Comment by julik** [comment]
Thanks for the reminder @AlexRiedler been crazy busy. Looks good to me, I think we need to see how this will influence stuff in production. Also since Patron is (at this point) below 1.0 we are still under the semver threshold of having no breaking changes, so I'm putting this through and we'll see where we end up. ❤️

**Pull request merged**
