### PR TITLE
Add Ruby progress callback + customise our GIL unblock function

### LINKED ISSUE #150: Respond to signals when outside the GIL
Currently Patron unlocks the GIL while performing the curl call. This is really good for enabling true parallelism, but Ruby does not trap signals when a Patron call is in progress. Signals also do not get delivered once the curl call completes. This can be problematic if an application performing a long Patron call has to be stopped or restarted - `kill -9` is pretty much the only option to deal with this, and it's really not very gentle. At least for the basic set of signals (`SIGINT`, ` SIGTERM`) Patron should provide a way to bail out of the curl call and yield control back to Ruby. This has to be done either with an unblock function or by installing custom interrupt handlers within the patron call, obviously with care to tear them down later.

### PR DESCRIPTION
**Pull request by julik**
We should provide some ability for users to re-acquire the GIL and call Ruby callback blocks. We will start with a progress callback which can be used for progress bars and speed computation. We also need to alter the way we unblock the thread so that we correctly handle signals.

This adds the following API:

```
sess.progress_callback = ->(download_total, download_now, upload_total, upload_now) {
  progress_bar.update(download_total) # ...or other interesting actions
}
```

The GIL will only be reacquired if this is configured on the Session/Request objects, otherwise we proceed through the same fast path as before with the GIL unlocked.

Closes #150 and paves the way for making #139 possible

### CODE REVIEW

**Comment by julik** [comment]
#150 and should open the door for #139 (because we need to manage the GIL very carefully for these). Also is going to allow programmatic abort from a callback proc, which can be a neat feature to have.

**Comment by julik** [comment]
@marshall-lee since you stumbled upon this anyway - have you got an idea what I should use instead of `rb_thread_call_with_gvl` when we only have `rb_thread_blocking_region` available (for pre-2.2 Rubies). I've been looking around but it seems all the docs online now only mention `rb_thread_blocking_region` being removed.

**Comment by julik** [comment]
@toland ?

**Comment by toland** [comment]
LGTM.

**Pull request merged**
